name: digitag
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase: ^9.0.2
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.3
  flutter_switch: ^0.3.2
  flutter_zoom_drawer: ^2.3.1
  get: 4.6.1
  google_fonts: ^2.3.1
  matrix4_transform: ^2.0.1
  qu_qr_code_scanner: ^0.1.4+2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/sofiapro.ttf

    - family: Sofia
      fonts:
        - asset: assets/fonts/Sofia-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/DiGi-Tag Logo 2.png"
