name: digitag
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase: ^9.0.2
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  get: 4.6.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/sofiapro.ttf
