name: digitag
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  badges: null
  cloud_firestore: ^3.1.9
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.3
  file_picker: ^4.5.1

  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_messaging: ^11.3.0
  firebase_storage: ^10.2.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.3
  flutter_switch: ^0.3.2
  flutter_zoom_drawer: ^2.3.1
  fluttertoast: ^8.0.9
  get: ^4.6.1
  google_fonts: ^2.3.1
  image_picker: ^0.8.5
  matrix4_transform: ^2.0.1
  mobile_scanner: ^1.0.0
  path_provider: ^2.0.9
  photo_view: ^0.13.0
  pinput: ^2.2.7
  qr_flutter: ^4.0.0
  screenshot: ^1.2.3
  share_plus: ^4.0.4


  firebase_messaging: ^11.3.0
  flutter_local_notifications: ^9.5.0
  http: ^0.13.4

  shared_preferences: ^2.0.13

  url_launcher: ^6.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/profile_icons/
    - assets/icons/social/

  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/sofiapro.ttf

    - family: Sofia
      fonts:
        - asset: assets/fonts/Sofia-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/DiGi-Tag Logo 2.png"
